# Generated by Django 5.2.17 on 2026-08-13 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meeting_id', models.CharField(editable=False, help_text='Auto-generated public ID (format: abc-defg-hij).', max_length=12, unique=True)),
                ('meeting_type', models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled')], help_text="'instant' or 'scheduled'.", max_length=10)),
                ('title', models.CharField(default='Instant Meeting', help_text="Meeting title. Defaults to 'Instant Meeting' for instant-type meetings.", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional agenda or description.', null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='Planned start time. NULL for instant meetings.', null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Meeting duration in minutes (1–1440).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', help_text='Current meeting lifecycle status.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of when the meeting record was created.')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1)), name='meeting_duration_positive')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text='Display name entered by the participant.', max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of when the participant joined.')),
                ('left_at', models.DateTimeField(blank=True, help_text='UTC timestamp of when the participant left. NULL if still in the meeting.', null=True)),
                ('meeting', models.ForeignKey(help_text='The meeting this participant joined.', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
    ]
